# Generated by Django 4.1.7 on 2023-03-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='preview',
        ),
    ]
