# Generated by Django 4.1.7 on 2023-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='Not ProvidedManipulated HTML', max_length=120),
        ),
    ]
