# Generated by Django 4.1.7 on 2023-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='detailedAddress',
            field=models.TextField(default='detailed address'),
            preserve_default=False,
        ),
    ]
