# Generated by Django 4.1.7 on 2023-04-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_shippingaddress_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='detailedAddress',
            field=models.TextField(help_text='Hello, Form the server side!'),
        ),
    ]
