# Generated by Django 4.1.7 on 2023-04-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_shippingaddress_detailedaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='detailedAddress',
            field=models.TextField(),
        ),
    ]
